### ISSUE TITLE
Computing gradients through the pretrained JMP models

### ISSUE THREAD

**Issue by jeevster** [facebookresearch/JMP#4]
I would like to be able to compute the gradient of the energy or force output of the pretrained JMP model with respect to the input atomic coordinates. I am unable to achieve this using `torch.autograd.grad`. I get the following error:
`One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.`

I have ensured that `batch.pos.requires_grad` is True and that there is a gradient tape tracked for energy and forces (i.e neither are leaf tensors). Any ideas why `batch.pos`  is seemingly not tracked in the gradient tape?

I have included a minimum reproducible example of the error using the jmp-s checkpoint on Transition-1x.

```python
import os
from tqdm import tqdm
import argparse
import lmdb
from pathlib import Path
import numpy as np
import torch
from torch.utils.data import DataLoader
from jmp.configs.pretrain.jmp_l import jmp_l_pt_config_
from jmp.datasets.pretrain_lmdb import PretrainLmdbDataset, PretrainDatasetConfig
from jmp.tasks.pretrain import PretrainConfig, PretrainModel
from jmp.tasks.pretrain.module import (
    NormalizationConfig,
    PretrainDatasetConfig,
    TaskConfig,
)


# Let's make the config
def jmp_l_config(data_path):
    config = PretrainConfig.draft()
    jmp_l_pt_config_(config)
    # Set data config
    config.batch_size = 4
    config.num_workers = 8
    config.backbone.otf_graph = True

    # Set the tasks
    config.tasks = [
        TaskConfig(
            name="transition1x",
            train_dataset=PretrainDatasetConfig(
                src=Path(os.path.join(data_path, "train")),
            ),
            val_dataset=PretrainDatasetConfig(
                src=Path(os.path.join(data_path, "val")),
            ),
            energy_loss_scale=1.0,
            force_loss_scale=14.0,
            normalization={
                "y": NormalizationConfig(mean=0.0, std=1.787466168382901),
                "force": NormalizationConfig(mean=0.0, std=0.3591422140598297),
            },
        ),
    ]
    return config.finalize()


def compute_grads(config, data_path, ckpt_path):

    ckpt_path = Path(ckpt_path)
    model = PretrainModel(config)
    # Load the checkpoint
    state_dict = torch.load(ckpt_path)
    sd = state_dict["state_dict"].copy()
    new_sd = {}
    # Map key to the right spot since only doing trans1x for now
    for k in sd:
        # TODO: make sure that this is the transition 1x head
        if "output.out_energy.3" in k:
            new_k = k.replace("output.out_energy.3", "output.out_energy.0")
            new_sd[new_k] = sd[k]
        elif "output.out_forces.3" in k:
            new_k = k.replace("output.out_forces.3", "output.out_forces.0")
            new_sd[new_k] = sd[k]
        elif "output.out_forces" in k or "output.out_energy" in k:
            pass
        else:
            new_sd[k] = sd[k]

    model.load_state_dict(new_sd, strict=False)
    model.to("cuda")

    dataset = model.train_dataset()

    dataloader = DataLoader(
        dataset,
        batch_size=32,
        shuffle=False,
        collate_fn=model.collate_fn,
    )

    batch = dataloader.__iter__().__next__()
    batch = batch.to("cuda")
    batch.pos.requires_grad = True

    energy, forces = model(batch)

    # Attempt to compute the gradient of the energy or force w.r.t. to the position
    # This fails with the error: "RuntimeError: One of the differentiated Tensors appears to not have been used in the graph.
    #  Set allow_unused=True if this is the desired behavior."
    assert energy.requires_grad
    assert forces.requires_grad
    assert not energy.is_leaf
    assert not forces.is_leaf
    energy_grad = torch.autograd.grad(energy.sum(), batch.pos, retain_graph=True)
    forces_grad = torch.autograd.grad(forces.sum(), batch.pos, retain_graph=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--checkpoint_path",
        type=str,
        help="Path to the jmp-l.pt or jmp-s.pt checkpoint.",
    )
    parser.add_argument(
        "--data_path",
        type=str,
        help="Path to the Transition 1x data.",
    )

    args = parser.parse_args()
    config = jmp_l_config(data_path=args.data_path)
    configs: list[tuple[PretrainConfig, type[PretrainModel]]] = []
    configs.append((config, PretrainModel))
    compute_grads(config, args.data_path, args.checkpoint_path)

```

**Comment by jeevster** [comment]
From doing some more digging, it looks like something special is being done in the finetuning module (which is not being done in the pretraining module) to enable gradient-based forces (see [here](https://github.com/facebookresearch/JMP/blob/main/src/jmp/tasks/finetune/energy_forces_base.py#L183-L194)). A naive copy-paste of this snippet into the pretrain module [forward pass](https://github.com/facebookresearch/JMP/blob/main/src/jmp/tasks/pretrain/module.py#L417-L420) doesn't quite work, since the `self.generate_graphs_transform(data)`method doesn't exist for the `PretrainModule` class. 

Any thoughts on how invasive/involved the change would be to enable differentiating through the pretrained model?

**Comment by nimashoghi** [comment]
Apologies for the delayed response -- busy week for me. 

I think the problem here is coming from the fact that during pertaining, we compute the radius graphs using a dataset transform on the CPU, prior to batching (as we need to use PBC for OC20/22 but not for ANI1x/Transition1x). The edge displacement vectors are also being computed on the CPU (in the same dataset transform). This means that in this case, positions are not actually linked to the edge displacement vectors in the computation graph. 

For your use case, I think the easiest way would be to recompute the graph displacement vectors in the beginning of the model's forward pass. This should produce the same exact displacement vectors, but now these should linked to the computation graph. 

The fine-tuning module implementation doesn't have this problem because the graph generation can just be performed on the GPU in the forward pass, as we're only dealing with a single fine-tuning dataset. 

Please let me know if that makes sense. Otherwise, I can write some pseudo code for you.

**Comment by jeevster** [comment]
Yes, that does make sense. I've tried a couple things, like commenting out the call to `self._generate_graphs` in the `transition1x_transform` [here](https://github.com/facebookresearch/JMP/blob/main/src/jmp/tasks/pretrain/module.py#L969) and instead placing it in the forward call of `PretrainModule` [here](https://github.com/facebookresearch/JMP/blob/main/src/jmp/tasks/pretrain/module.py#L417). That doesn't quite work, because it seems like there are other transformations happening after `self._generate_graphs` which rely on its output. If I perform the transform in both the `transition1x_transform` and `PretrainModule` forward call, the second call produces fields which are different from the first call (again, I'm guessing this is because there are other things that need to be called after `self._generate_graphs`). 

Some slightly lower-level guidance on this would be much appreciated!

**Comment by nimashoghi** [comment]
Just to clarify, have you tried recomputing the displacement vectors as I suggested above? Here's a basic implementation of what I mean: https://gist.github.com/nimashoghi/2e950812069bc9c10913ac411a00ffd8

I currently don't have this version of the JMP environment set up so I can't test the above code. Let me know if you run into any issues and I'll try to resolve them the best I can.

P.S. The code above looks kind of complicated because GemNet OC operates on 4 different graphs; as such, we need to store the relevant graph information for each graph into the `torch_geometric.data.Batch` object.

**Comment by jeevster** [comment]
Ah, I see. This works, thanks!
